### ISSUE TITLE
gff3 files are not zero-based

### ISSUE THREAD

**Issue by joseja** [bioinfologics/satsuma2#1]
~ SatsumaToGFF -i satsuma_summary.chained.out | sort -k1,1 -k3,3 | head -n 1
`scaffold_1	Satsuma	block	0	339		-	.	ID=sblock_1850;Name=sblock_1850;Target=Chr01`

But gff3 files are one-based in the specs, so the first base should be 1, not 0.
For info about zero-based and one-based formats in bioinformatics:
https://www.biostars.org/p/84686/

In fact, if you try to manipulate that file, it gives error downstream (as expected). Eg.
~ SatsumaToGFF -i satsuma_summary.chained.out | sort -k1,1 -k3,3 | head -n 1 | bedtools sort -i -
`Error: malformed GFF entry at line 1. Start was greater than end. Exiting.
`

**Comment by jonwright99** [comment]
I've pushed an update to fix this.  You will need to get the latest version of the code and recompile.
