### ISSUE TITLE
satsuma 3

### ISSUE THREAD

**Issue by mictadlo** [bioinfologics/satsuma2#13]
Hi,
Where do I get satsuma 3 from? There three repositories 

- https://sourceforge.net/projects/satsuma/ or 
- ftp://ftp.broadinstitute.org/distribution/software/spines/satsuma-3.0.tar.gz
- is this repository for the newest one?

Thank you in advance,

Michal

**Comment by jonwright99** [comment]
Hi Michal, this repository is the newest version - Satsuma2. The other repositories are versions of Satsuma v1
