### ISSUE TITLE
Citing Satsuma2

### ISSUE THREAD

**Issue by fergsc** [bioinfologics/satsuma2#15]
Have been using satsuma2 and would like to cite it. Whats the best way to do this?

**Comment by bjclavijo** [comment]
It's great that you've been making good use of Satsuma2!
Sadly, we have not finished the manuscript (it's been halted for more than a year, really) so I would recommend that you cite Satsuma, and cite Satsuma2 just by using the URL. We can also get a DOI through Zenodo or something like that for the repository, I guess.

**Comment by fergsc** [comment]
Thanks, I shall just cite the url.
