### ISSUE TITLE
homologous comparison

### ISSUE THREAD

**Issue by mictadlo** [bioinfologics/satsuma2#17]
Hi, 
I ran satsuma with default settings to do a homologous comparison. Looking at MizBee output each chromosome match to its own. I would have expected to see that they would be other relationships between the chromosomes. Or do I have to use different settings for homologous comparison?

Thank you in advance,

Michal

**Comment by jonwright99** [comment]
Hi Michal,

Satsuma is designed to find the single best match so comparing all-to-all will **only** find the matching chromosome. One way to find the best secondary matches would be to compare each chromosome to all the others **except** itself, however this would not find any additional matches (third best etc.). Satsuam2 is not really designed for this type of comparison out of the box and there are probably better tools to use, eg. orthoMCL for gene-based comparisons.

Best,
Jon
