### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by KristinaGagalova** [bioinfologics/satsuma2#18]
Hi, 
I am having the following error during installation:
```
make
[  1%] Building CXX object CMakeFiles/SatsumaToGFF.dir/tools/analysis/SatsumaToGFF.cc.o
c++: error: unrecognized command line option ‘-std=c++14’
make[2]: *** [CMakeFiles/SatsumaToGFF.dir/tools/analysis/SatsumaToGFF.cc.o] Error 1
make[1]: *** [CMakeFiles/SatsumaToGFF.dir/all] Error 2
make: *** [all] Error 2
```

Versions below
g++ (GCC) 8.2.0
cmake version 3.12.4

Do you know what that can be? 
Thank you in advance

**Comment by KristinaGagalova** [comment]
Ok, I changed the string "-std=c++14" in the header of the file CMake.list and looks like it's working.

**Comment by RGCheek** [comment]
Hi Kristina,

I'm having the same issue. What did you change the -std=c++14 string to?

Thank you,

Rebecca
