### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by QindongTang** [bioinfologics/satsuma2#20]
Hi It seems the program stops at the waiting for seed pre-filters and I ran the SatsumaSynteny2 using the default parameter with thread=4
Running seed pre-filter: 
  ./bin/KMatch zebrafinch_ChrZ.fasta /home/tang/database/RepeatMasker/riparia/riparia.fasta.masked 29 zebraChrZ_riparia/kmatch_results.k29 29 28 1; touch zebraChrZ_riparia/kmatch_results.k29.finished
Running seed pre-filter: 
  ./bin/KMatch zebrafinch_ChrZ.fasta /home/tang/database/RepeatMasker/riparia/riparia.fasta.masked 31 zebraChrZ_riparia/kmatch_results.k31 31 30 1; touch zebraChrZ_riparia/kmatch_results.k31.finished
Waiting for seed pre-filters...
Thanks for any suggestion

**Comment by jonwright99** [comment]
Hi,
Once KMatch has found the seeds, slaves are spawned to compare the chunks. It looks like Kmatch is completing but the slaves are not being spawned. Do you get any other error? Are you using a submission system to run the KMatch jobs and slaves, ie. the bit in the satsuma_run.sh file.

**Comment by QindongTang** [comment]
Thanks very much for your reply.

It actually failed to open the ./bin/satsuma_run.sh. Now the problem is solved.

________________________________
