### ISSUE TITLE
Unable to find satsuma_run.sh

### ISSUE THREAD

**Issue by dthorburn** [bioinfologics/satsuma2#26]
Hi, 

I am trying to run SatsumaSynteny2 on our HPC, but it appears I keep getting the same error when slaves jobs are being created.

Running the command:
`SatsumaSynteny2 -q $Ref_Geno1/tig00000011_pilon.fa -t $Ref_Geno2/Gac-HiC_revised_genome_assembly.fasta -o $OUT_DIR/`

I then get the following error:
`sh: :/data/home/btx316/privatemodules/satsuma2/bin/satsuma_run.sh: No such file or directory`

The head of the output file is:
`SATSUMA: Welcome to SatsumaSynteny! Current date and time: 2020/02/27 12:57:51
Path for Satsuma2: ':/data/home/btx316/privatemodules/satsuma2/bin'
Executing /data/home/btx316/privatemodules/satsuma2/bin/SatsumaSynteny2
Setting up grid.
Preparing...
select=0	chunks=150742
chunks: 150742
select=0	chunks=47
chunks: 47
size x=6281 y=2 size=12562
Initializing multimatches...
Done.
SATSUMA: Acquiring seeds, date and time: 2020/02/27 12:58:01
Running seed pre-filter: 
  :/data/home/btx316/privatemodules/satsuma2/bin/KMatch /data/SBCS-EizaguirreLab/Miles/CompGenomics_Collab/00_Ref_Genomes/Gynogene_Genome/All_Contigs_Ind/tig00000011_pilon.fa /data/SBCS-EizaguirreLab/Miles/CompGenomics_Collab/00_Ref_Genomes/Peichel_Genome/Gac-HiC_revised_genome_assembly.fasta 11 /data/scratch/btx316/Comp_Genomics/08_Satsuma2/02_IndContigs_Satsuma2/tig00000011_pilon.fa/kmatch_results.k11 11 10 1; touch /data/scratch/btx316/Comp_Genomics/08_Satsuma2/02_IndContigs_Satsuma2/tig00000011_pilon.fa/kmatch_results.k11.finished
sh: :/data/home/btx316/privatemodules/satsuma2/bin/satsuma_run.sh: No such file or directory`

The contents of the binary directory is
`$ ls /data/home/btx316/privatemodules/satsuma2/bin/
BlockDisplaySatsuma  FilterGridSeeds       MatchesByFeature         ReverseSatsumaOut  SortSatsuma
ChainMatches         HomologyByXCorr       MergeScaffoldsBySynteny  satsuma_run.sh
Chromosemble         HomologyByXCorrSlave  MergeXCorrMatches        SatsumaSynteny2
ChromosomePaint      KMatch                MicroSyntenyPlot         SatsumaToFASTA
ColaAlignSatsuma     MatchDump             OrderOrientBySynteny     SatsumaToGFF`

And satsuma_run.sh exists and exectutes when I submit `sh satsuma_run.sh`.

In case it's important I used gcc/7.1.0 and cmake/3.16.0 to compile.

**Comment by jonwright99** [comment]
Hi,
Can you check you are exporting the SATSUMA2_PATH correctly before you run Satsuma2. It looks like you are setting it to ```:/data/home/btx316/privatemodules/satsuma2/bin/``` rather than ```/data/home/btx316/privatemodules/satsuma2/bin/```, ie. adding an extra colon to the start.

**Comment by dthorburn** [comment]
Hey, 
Thanks for the quick response. I can't believe I missed something so obvious - I had just finished building a singularity container and hadn't make the same mistake and it seemed to work there.
