### ISSUE TITLE
do_refine option in SatsumaSynteny2

### ISSUE THREAD

**Issue by hughesdj** [bioinfologics/satsuma2#3]
Running SatsumaSynteny2 with the do_refine option set gives an error, because shell cannot find HomologyByXCorr.
@grabherr  Should the shell call HomologyByXCorrSlave as it does earlier?

Command:
`$prog_path"SatsumaSynteny2" -t $target -q $query -o out2 -do_refine 1 -slaves 8 -threads 8`

Output tail:
`..
Merging XCorr matches: 
  /home/apps/rothhpc1-cluster/src/satsuma2/satsuma2-master/bin/MergeXCorrMatches -i out2/xcorr_aligns.final.out -q /home/data/hughesdj/Duplication/satsuma/Svim_scaffs.fa -t /home/data/hughesdj/Duplication/satsuma/Spur_19Chrs.fa -o out2/satsuma_summary.chained.out > out2/MergeXCorrMatches.chained.out
== Processing finished, waiting for the slaves to die ==
TIME SPENT WORKING: 15551
== Processing finished, waiting for the slaves to die ==
TIME SPENT WORKING: 15552
Running refined matches (fill in the blanks): 
  /home/apps/rothhpc1-cluster/src/satsuma2/satsuma2-master/bin/HomologyByXCorr -cutoff 1.2  -q /home/data/hughesdj/Duplication/satsuma/Svim_scaffs.fa -t /home/data/hughesdj/Duplication/satsuma/Spur_19Chrs.fa -o out2/xcorr_aligns.refined.out -guide out2/xcorr_aligns.final.out > out2/HomologyByXCorr.refined.out
sh: /home/apps/rothhpc1-cluster/src/satsuma2/satsuma2-master/bin/HomologyByXCorr: No such file or directory
Merging XCorr matches: 
  /home/apps/rothhpc1-cluster/src/satsuma2/satsuma2-master/bin/MergeXCorrMatches -i out2/xcorr_aligns.refined.out -q /home/data/hughesdj/Duplication/satsuma/Svim_scaffs.fa -t /home/data/hughesdj/Duplication/satsuma/Spur_19Chrs.fa -o out2/satsuma_summary.refined.out > out2/MergeXCorrMatches.refined.out
terminate called after throwing an instance of 'CMException'
sh: line 1: 68774 Aborted                 /home/apps/rothhpc1-cluster/src/satsuma2/satsuma2-master/bin/MergeXCorrMatches -i out2/xcorr_aligns.refined.out -q /home/data/hughesdj/Duplication/satsuma/Svim_scaffs.fa -t /home/data/hughesdj/Duplication/satsuma/Spur_19Chrs.fa -o out2/satsuma_summary.refined.out > out2/MergeXCorrMatches.refined.out
Joining Workqueue thread
SATSUMA: all done, date and time: 2016/08/11 18:48:02`

**Comment by bjclavijo** [comment]
HomologyByXCorr should have been built. It seems there's a bunch of missing binaries there. We'll have a look.

**Comment by jonwright99** [comment]
@hughesdj can you tell me which binaries you have in /home/apps/rothhpc1-cluster/src/satsuma2/satsuma2-master/bin/.  Compiling should create the following;

BlockDisplaySatsuma
ChainMatches
Chromosemble
ChromosomePaint
ColaAlignSatsuma
FilterGridSeeds
HomologyByXCorrSlave
KMatch
MatchDump
MatchesByFeature
MergeScaffoldsBySynteny
MergeXCorrMatches
MicroSyntenyPlot
OrderOrientBySynteny
ReverseSatsumaOut
satsuma_run.sh
SatsumaSynteny2
SatsumaToFASTA
SatsumaToGFF
SortSatsuma

**Comment by jonwright99** [comment]
and now I see that HomologyByXCorr isn't compiled. Sorry, being a bit slow today.  I'll patch this.

**Comment by hughesdj** [comment]
@jonwright99  Thanks, yes all the binaries listed above are present, but not HomologyByXCorr, which shell calls when do_refine option is set.
Were you able to fix?  Is issue closed?
