### ISSUE TITLE
Satsuma for more than 2 species

### ISSUE THREAD

**Issue by madzayasodara** [bioinfologics/satsuma2#9]
Hi!
is it possible to run satsuma for more than 2 species at the same time? Lets say 3.
If not would you advise on any other tool?
Thanks!

**Comment by grabherr** [comment]
Hi,

Currently not, that was the plan for Satsuma 3; have you checked the 
usual suspects, lastz etc.? Do you need to do his truly reference 
independent?

Cheers,

- Manfred

**Comment by mictadlo** [comment]
Using usual suspects, like for example lastz, how is it possible to convert it to MizBee format?

**Comment by jonwright99** [comment]
I guess you would have to write a custom script to convert the output to MizBee format.
